// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Profile interface {
	IsProfile()
}

type ProfileDetail interface {
	IsProfileDetail()
}

type OfficalsProfile struct {
	Role        string `json:"role"`
	Description string `json:"description"`
}

func (OfficalsProfile) IsProfileDetail() {}

type OfficalsProfileInput struct {
	Role        string  `json:"role"`
	Description *string `json:"description"`
}

type SignUpInput struct {
	Name      string  `json:"name"`
	Nickname  *string `json:"nickname"`
	Password  string  `json:"password"`
	PhoneCode string  `json:"phoneCode"`
}

type StudentProfile struct {
	Grade  int `json:"grade"`
	Class  int `json:"class"`
	Number int `json:"number"`
}

func (StudentProfile) IsProfileDetail() {}

type StudentProfileInput struct {
	Grade  int `json:"grade"`
	Class  int `json:"class"`
	Number int `json:"number"`
}

type TeacherProfile struct {
	Subject []string `json:"subject"`
}

func (TeacherProfile) IsProfileDetail() {}

type TeacherProfileInput struct {
	Subject []string `json:"subject"`
}
